version: "3.0"
services:
  web:
    build:
      dockerfile: Dockerfile
      image: registry.heroku.com/grassrootshospitality/web
    cached: true
    environment:
      - "SECRET_KEY=insecure - only for testing"
    links:
      - postgres
  postgres:
    image: postgres
  worker:
    build:
      dockerfile: Dockerfile
      image: registry.heroku.com/grassrootshospitality/worker
      args:
        CUSTOM_CMD: ./manage.py celeryd
    cached: true
  dockercfg_generator:
    image: codeship/heroku-dockercfg-generator
    add_docker: true
    encrypted_env_file: .codeship/heroku.env.encrypted
